name: hrm.hrm_act_v3@HierarchicalReasoningModel_ACTV3
loss:
  name: losses@ACTLossHead
  loss_type: stablemax_cross_entropy

halt_exploration_prob: 0.1
halt_max_steps: 16

H_layers: 4
L_layers: 4

hidden_size: 256
num_heads: 8  # min(2, hidden_size // 64)
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope

# Use float16 for better memory efficiency
forward_dtype: float16
